/**
 * Sample Data for Demo Seed Database
 *
 * Rich, realistic data arrays for generating demo content
 */

// First names from diverse international backgrounds
export const firstNames = [
	// Western names
	"James",
	"John",
	"Robert",
	"Michael",
	"William",
	"David",
	"Richard",
	"Joseph",
	"Thomas",
	"Charles",
	"Mary",
	"Patricia",
	"Jennifer",
	"Linda",
	"Barbara",
	"Elizabeth",
	"Susan",
	"Jessica",
	"Sarah",
	"Karen",
	"Christopher",
	"Daniel",
	"Matthew",
	"Anthony",
	"Mark",
	"Donald",
	"Steven",
	"Paul",
	"Andrew",
	"Joshua",
	"Emily",
	"Emma",
	"Olivia",
	"Ava",
	"Isabella",
	"Sophia",
	"Charlotte",
	"Mia",
	"Amelia",
	"Harper",

	// Asian names
	"Wei",
	"Min",
	"Juan",
	"Ming",
	"Hui",
	"Lei",
	"Yan",
	"Li",
	"Chen",
	"Wang",
	"Yuki",
	"Haruto",
	"Sakura",
	"Hina",
	"Takeshi",
	"Kenji",
	"Akira",
	"Yui",
	"Ren",
	"Sora",
	"Ji-ho",
	"Min-jun",
	"Seo-yeon",
	"Ji-woo",
	"Hye-jin",
	"Sung-min",
	"Dong-hyun",
	"Mi-young",
	"Arjun",
	"Priya",
	"Rahul",
	"Anjali",
	"Vikram",
	"Deepika",
	"Rohan",
	"Kavya",
	"Aditya",
	"Shreya",
	"Nguyen",
	"Tran",
	"Pham",
	"Le",
	"Hoang",
	"Vo",
	"Dang",
	"Bui",
	"Do",
	"Ngo",

	// Middle Eastern names
	"Mohammed",
	"Ahmed",
	"Ali",
	"Omar",
	"Hassan",
	"Fatima",
	"Aisha",
	"Zahra",
	"Layla",
	"Nour",
	"Ibrahim",
	"Youssef",
	"Khaled",
	"Amira",
	"Mariam",
	"Sara",
	"Rania",
	"Dina",
	"Hana",
	"Lina",

	// African names
	"Kofi",
	"Kwame",
	"Abena",
	"Akua",
	"Chinwe",
	"Obinna",
	"Amara",
	"Chukwu",
	"Sekou",
	"Fatou",
	"Mandela",
	"Nkosi",
	"Thabo",
	"Zanele",
	"Sipho",
	"Nomsa",
	"Kagiso",
	"Lerato",

	// Latin American names
	"Miguel",
	"José",
	"Carlos",
	"Juan",
	"Luis",
	"María",
	"Ana",
	"Carmen",
	"Rosa",
	"Isabel",
	"Diego",
	"Alejandro",
	"Javier",
	"Sofia",
	"Valentina",
	"Camila",
	"Isabella",
	"Martina",

	// European names
	"Luca",
	"Marco",
	"Alessandro",
	"Giulia",
	"Francesca",
	"Chiara",
	"Sofia",
	"Elena",
	"Pierre",
	"Jean",
	"Marie",
	"Sophie",
	"Camille",
	"Lucas",
	"Emma",
	"Léa",
	"Hans",
	"Klaus",
	"Anna",
	"Julia",
	"Maximilian",
	"Felix",
	"Laura",
	"Sarah",
	"Ivan",
	"Dmitri",
	"Olga",
	"Natasha",
	"Alexei",
	"Tatiana",
	"Mikhail",
	"Svetlana",
];

// Last names from diverse international backgrounds
export const lastNames = [
	// Western last names
	"Smith",
	"Johnson",
	"Williams",
	"Brown",
	"Jones",
	"Garcia",
	"Miller",
	"Davis",
	"Rodriguez",
	"Martinez",
	"Hernandez",
	"Lopez",
	"Gonzalez",
	"Wilson",
	"Anderson",
	"Thomas",
	"Taylor",
	"Moore",
	"Jackson",
	"Martin",
	"Lee",
	"Thompson",
	"White",
	"Harris",
	"Clark",
	"Lewis",
	"Robinson",
	"Walker",
	"Young",
	"Hall",
	"Allen",
	"King",
	"Wright",
	"Scott",
	"Green",
	"Baker",
	"Adams",
	"Nelson",
	"Carter",
	"Mitchell",

	// Asian last names
	"Wang",
	"Li",
	"Zhang",
	"Liu",
	"Chen",
	"Yang",
	"Huang",
	"Zhao",
	"Wu",
	"Zhou",
	"Tanaka",
	"Suzuki",
	"Takahashi",
	"Watanabe",
	"Ito",
	"Yamamoto",
	"Nakamura",
	"Kobayashi",
	"Kato",
	"Yoshida",
	"Kim",
	"Park",
	"Lee",
	"Choi",
	"Jung",
	"Kang",
	"Cho",
	"Yoon",
	"Jang",
	"Lim",
	"Singh",
	"Kumar",
	"Patel",
	"Sharma",
	"Gupta",
	"Reddy",
	"Rao",
	"Iyer",
	"Nair",
	"Menon",
	"Nguyen",
	"Tran",
	"Le",
	"Pham",
	"Hoang",
	"Vu",
	"Dang",
	"Bui",
	"Do",
	"Ngo",

	// Middle Eastern last names
	"Al-Rashid",
	"Al-Farsi",
	"Al-Sayed",
	"Hassan",
	"Hussein",
	"Khalil",
	"Mansour",
	"Nasser",
	"Qasim",
	"Saleh",

	// African last names
	"Okafor",
	"Okonkwo",
	"Adeola",
	"Mensah",
	"Diop",
	"Mbeki",
	"Nkrumah",
	"Mandela",
	"Tutu",
	"Nyerere",

	// European last names
	"Müller",
	"Schmidt",
	"Schneider",
	"Fischer",
	"Weber",
	"Meyer",
	"Wagner",
	"Becker",
	"Schulz",
	"Hoffmann",
	"Dupont",
	"Martin",
	"Bernard",
	"Dubois",
	"Thomas",
	"Robert",
	"Richard",
	"Petit",
	"Durand",
	"Leroy",
	"Rossi",
	"Russo",
	"Ferrari",
	"Esposito",
	"Bianchi",
	"Romano",
	"Colombo",
	"Ricci",
	"Marino",
	"Greco",
	"García",
	"Rodríguez",
	"Martínez",
	"López",
	"González",
	"Pérez",
	"Sánchez",
	"Ramírez",
	"Torres",
	"Flores",
];

// Top universities worldwide
export const universities = [
	"Harvard University",
	"Stanford University",
	"Massachusetts Institute of Technology",
	"University of Cambridge",
	"University of Oxford",
	"California Institute of Technology",
	"Princeton University",
	"Yale University",
	"University of Chicago",
	"Columbia University",
	"ETH Zurich",
	"University of Tokyo",
	"Imperial College London",
	"University of Pennsylvania",
	"Johns Hopkins University",
	"University of California Berkeley",
	"Cornell University",
	"University of Toronto",
	"McGill University",
	"University of Melbourne",
	"Australian National University",
	"National University of Singapore",
	"Nanyang Technological University",
	"University of Hong Kong",
	"Seoul National University",
	"Peking University",
	"Tsinghua University",
	"University of Edinburgh",
	"University of Manchester",
	"King's College London",
	"London School of Economics",
	"University of Munich",
	"Technical University of Munich",
	"Heidelberg University",
	"University of Amsterdam",
	"Delft University of Technology",
	"Karolinska Institute",
	"University of Copenhagen",
	"Uppsala University",
	"Lund University",
	"University of British Columbia",
	"University of Sydney",
	"University of Queensland",
	"Monash University",
	"University of Auckland",
	"Sorbonne University",
	"École Polytechnique",
	"Sciences Po Paris",
	"Bocconi University",
	"Politecnico di Milano",
	"Sapienza University of Rome",
	"KU Leuven",
];

// Countries for study destinations
export const countries = [
	"United States",
	"United Kingdom",
	"Canada",
	"Australia",
	"Germany",
	"France",
	"Netherlands",
	"Switzerland",
	"Sweden",
	"Denmark",
	"Norway",
	"Finland",
	"Singapore",
	"Japan",
	"South Korea",
	"China",
	"Hong Kong",
	"Taiwan",
	"New Zealand",
	"Ireland",
	"Belgium",
	"Austria",
	"Italy",
	"Spain",
	"Portugal",
	"Czech Republic",
	"Poland",
	"Hungary",
	"Estonia",
	"Israel",
	"United Arab Emirates",
	"Malaysia",
	"Thailand",
	"India",
	"Brazil",
	"Argentina",
	"Chile",
	"Mexico",
	"South Africa",
];

// Research areas and topics
export const researchAreas = [
	// Computer Science & Technology
	"Artificial Intelligence",
	"Machine Learning",
	"Deep Learning",
	"Natural Language Processing",
	"Computer Vision",
	"Robotics",
	"Human-Computer Interaction",
	"Cybersecurity",
	"Blockchain Technology",
	"Quantum Computing",
	"Cloud Computing",
	"Edge Computing",
	"Internet of Things",
	"Big Data Analytics",
	"Data Science",
	"Software Engineering",
	"Distributed Systems",
	"Computer Networks",
	"Database Systems",

	// Life Sciences & Medicine
	"Cancer Research",
	"Immunology",
	"Genetics and Genomics",
	"Neuroscience",
	"Molecular Biology",
	"Biotechnology",
	"Pharmacology",
	"Bioinformatics",
	"Regenerative Medicine",
	"Stem Cell Research",
	"Precision Medicine",
	"Public Health",
	"Epidemiology",
	"Medical Imaging",
	"Drug Discovery",

	// Engineering
	"Renewable Energy",
	"Sustainable Materials",
	"Nanotechnology",
	"Biomedical Engineering",
	"Environmental Engineering",
	"Aerospace Engineering",
	"Mechanical Engineering",
	"Electrical Engineering",
	"Chemical Engineering",
	"Civil Engineering",
	"Materials Science",
	"Energy Storage",

	// Physical Sciences
	"Climate Change",
	"Astrophysics",
	"Particle Physics",
	"Condensed Matter Physics",
	"Quantum Physics",
	"Atmospheric Science",
	"Oceanography",
	"Geophysics",
	"Cosmology",
	"Theoretical Physics",

	// Social Sciences & Humanities
	"Behavioral Economics",
	"Political Science",
	"International Relations",
	"Sociology",
	"Psychology",
	"Cognitive Science",
	"Linguistics",
	"Anthropology",
	"History",
	"Philosophy",
	"Education",
	"Development Studies",
	"Urban Planning",
	"Public Policy",
	"Law and Society",

	// Business & Economics
	"Financial Technology",
	"Entrepreneurship",
	"Innovation Management",
	"Supply Chain Management",
	"Marketing Analytics",
	"Organizational Behavior",
	"Corporate Governance",
	"Sustainable Business",
	"Digital Economics",
	"International Trade",
];

// Degree levels
export const degreeLevels = [
	"Bachelor's",
	"Master's",
	"PhD",
	"Postdoctoral",
	"Certificate",
	"Diploma",
	"Associate",
	"Professional Degree",
	"Executive MBA",
];

// Program durations
export const programDurations = [
	"6 months",
	"1 year",
	"18 months",
	"2 years",
	"3 years",
	"4 years",
	"5 years",
];

// Attendance types
export const attendanceTypes = [
	"Full-time",
	"Part-time",
	"Online",
	"Hybrid",
	"On-campus",
	"Distance Learning",
	"Evening",
	"Weekend",
	"Block Schedule",
	"Self-paced",
];

// GPA requirements
export const gpaRequirements = [2.5, 2.75, 3.0, 3.25, 3.5, 3.75];

// Language certificates
export const languageCertificates = [
	{ name: "IELTS", minScore: "6.0", maxScore: "9.0" },
	{ name: "TOEFL iBT", minScore: "80", maxScore: "120" },
	{ name: "Cambridge English", minScore: "160", maxScore: "230" },
	{ name: "PTE Academic", minScore: "50", maxScore: "90" },
	{ name: "Duolingo", minScore: "100", maxScore: "160" },
];

// Standardized tests
export const standardizedTests = [
	{ name: "GRE", minScore: "300", maxScore: "340" },
	{ name: "GMAT", minScore: "400", maxScore: "800" },
	{ name: "SAT", minScore: "1000", maxScore: "1600" },
	{ name: "ACT", minScore: "20", maxScore: "36" },
];

// Scholarship amounts (in USD)
export const scholarshipAmounts = [
	2500, 5000, 7500, 10000, 12500, 15000, 20000, 25000, 30000, 40000, 50000,
	75000, 100000,
];

// Job salaries (annual in USD)
export const jobSalaries = [
	30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000, 120000, 150000,
	180000, 200000,
];

// Contract types
export const contractTypes = [
	"Permanent",
	"Fixed-term",
	"Temporary",
	"Project-based",
	"Internship",
	"Postdoctoral",
];

// Job types
export const jobTypes = [
	"Full-time",
	"Part-time",
	"Contract",
	"Research Assistant",
	"Teaching Assistant",
	"Postdoctoral Fellow",
	"Visiting Scholar",
	"Lecturer",
	"Professor",
];
